import type { Metadata } from "next";
import { Oswald,Poppins } from "next/font/google";
import "./globals.css";

const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${poppins.className} `}>{children}</body> */}
      <body className={`${oswald.className}`}>{children}</body>
    </html>
  );
}
